import pandas as pd
d={'Order ID':[101,102,103,104,105,106,107,108,109,110,111,112],'Customer':["Amit","Priya","Rahul","Sneha","Vikas","Neha","Rohan","Pooja","Rehan","Kajal","Umar","Sameer"],'Category':["Electronics","Electronics","Furniture","Electronics","Furniture","Stationery","Electronics","Stationery","Furniture","Electronics","Stationery","Electronics"],'Product':["Laptop","Mobile","Chair","Tablet","Table","Notebook","Mobile","Pen","Chair","Laptop","Notebook","Mobile"],'Quantity':[1,2,4,1,1,10,1,20,2,3,5,1,],'Price':[55000,18000,2500,15000,12000,200,20000,20,2600,600000,220,19000],'City':["Pune","Mumbai","Nashik","Pune","Bhusawal","Mumbai","Pune","Nashik","Jalgaon","Chopda","Dhule","Delhi"],'Date':pd.to_datetime(['2026-01-05','2026-01-06','2026-01-07','2026-01-08','2026-01-09','2026-01-10','2026-01-11','2026-01-12','2026-01-13','2026-01-14','2026-01-15','2026-01-16'])}
df=pd.DataFrame(d)
print(df)

print("========================================Part A Basic Filtering==========================")
print("=======Display Customer & Product Columns=======")
print(df[['Customer','Product']])
print("=======Display Category is Electroincs=======")
f1=(df[df['Category']=="Electronics"])
print(f1)
print("=======Quantity Greater Than Five=======")
quantity_g=(df[(df['Quantity']>5)])
print(quantity_g)
print("=======Display Price Less Than Equal To 1000=======")
price_l=(df[(df['Price']<=1000)])
print(price_l)
print("=======City Is Pune=======")
city_p=(df[(df['City']=="Pune")])
print(city_p)
print("=======Display Category Furniture,Price Greater Than 5000=======")
f2=(df[(df['Category']=="Furniture")&(df['Price']>5000)])
print(f2)

print("========================================Part B Advanced Filtering======================")
print("=======Display Rows Category is Electronics & Price Greater Than 15000======")
f3=(df[(df['Category']=="Electronics")&(df['Price']>15000)])
print(f3)
print("======Display Rows City Is Pune Or Mumbai======")
f4=(df[(df['City']=="Pune")|(df['City']=="Mumbai")])
print(f4)
print("=======Display Rows Porduct Is Laptop Or Mubail=======")
f5=(df[(df['Product']=="Laptop")|(df['Product']=="Mobile")])
print(f5)
print("=======Display Quantity Between 2 And 10=======")
f6=(df[(df['Quantity']>2)&(df['Quantity']<10)])
print(f6)
print("=======Display Customer Name Starts With 'A'=======")
f7=(df['Customer'].str.startswith('A'))
print(df.loc[f7])
print("=======Display Date Is On Or After 2024-01-10=======")
f8=(df[(df['Date']>'2024-01-10')])
print(f8)

print("========================================Part C Groupby & Aggregation==========================")
print("=======Total Sales Sum of price Quantity by Category=======")
f9=df['Sales']=df['Price']*df['Quantity']
category_s=df.groupby('Category')['Sales'].sum()
print(category_s)
print("=======Total Quantity Sold By Product=======")
f10=df['Sold']=df['Quantity']
sold=df.groupby('Product')['Sold'].sum()
print(sold)
print("=======Average Price by Category=======")
f11=df['Average']=df['Price']
avg=df.groupby('Category')['Average'].mean()
print(avg) 
print("=======Total Sale By City======")
f12=df['Sales']=df['Price']*df['Quantity']
total=df.groupby('City')['Sales'].sum()
print(total)
print("=======Number Of Orders Placed By Each Customer=======")
cust=df.groupby('Customer')['Order ID'].count()
print(cust)
print("=======Maximum & Minimum Price By Category=======")
d13=df.groupby('Price')['Category'].max()
print(d13)
d14=df.groupby('Price')['Category'].min()
print(d14)

print("========================================Part D Sorting & Top N==============================")
print("======Sort By Price In Descending Order======")
price1=df.sort_values(by='Price',ascending=False)
print(price1)
print("======Sort By Quantity In Ascending Order=======")
quantity1=df.sort_values(by='Quantity',ascending=False)
print(quantity1)
print("=======Top Five Expensive Order=======")
top5=df.sort_values(by='Price',ascending=False).head(5)
print(top5[['Order ID','Customer','Product','Price']])
print("=======Top Thee Product With Highest Total Sales======")
df['TotalSales']=df['Quantity']*df['Price']
top3=df.groupby('Product')['TotalSales'].sum().sort_values(ascending=False).head(3)
print(top3)

print("======================================Part E Date Operations================================")
print("=======New Columns Year From The Date Column=======")
df['Date']=pd.to_datetime(df['Date'])
df['Year']=df['Date'].dt.year
print(df[['Order ID','Date','Year']])
print("=======New Column Month From The Date Column=======")
df['Date']=pd.to_datetime(df['Date'])
df['Month']=df['Date'].dt.month
print(df[['Order ID','Date','Month']])
print("=======Total Sales By Year & Month======")
df['TotalSales']=df['Quantity']*df['Price']
df['Date']=pd.to_datetime(df['Date'])
df['Month']=df['Date'].dt.month
df['Year']=df['Date'].dt.year
totals=df.groupby(['Month','Year'])['TotalSales'].sum()
print(totals)
print("=======Order Was Placed On A Weekend Saturday Or Sunday=======")
df['Date']=pd.to_datetime(df['Date'])
week=df[df['Date'].dt.dayofweek>=5]
print(week)

print("======================================Part F Pivot Table===================================")
print("=======Pivot Table Show Total Sales By Category & City=======")
pivot=df.pivot_table(index=['Category','City'],values=['TotalSales'],aggfunc='sum')
print(pivot)
print("=======Pivot Table Show Total Quantity By Product & City=======")
pivot2=df.pivot_table(index=['Product','City'],values=['Quantity'],aggfunc='sum')
print(pivot2)

print("======================================Part G Data Cleaning================================")
print("=======Check Missing Values=======")
print(df.isnull().sum())
print("=======Replace Any Missing Values In Price With The Mean Price=======")
print(df['Price']==df['Price'].fillna(df['Price'].mean()))
print("=======Remove Duplicate Rows=======")
print(df.drop_duplicates())
print("=======Reset  Index Of The DataFrame=======")
print(df.reset_index(drop=True))

print("======================================Challenge Task====================================")
print("=======Total Sales By Category=======")
print(df.groupby('Category')['TotalSales'].sum())
print("=======Top Cities by Total Sales=======")
print(df.groupby('City')['TotalSales'].sum().sort_values(ascending=False).head(3))
print("=======Best Selling Product By Quantity=======")
print(df.groupby('Product')['Quantity'].sum())
print(df.groupby('Product')['Quantity'].sum().idxmax())
print("=======Total Number Of Order=======")
print(df['Order ID'].count())
print(len(df))
print("=======Average Order Value=======")
print(df['TotalSales'].mean())

print("=====================================COMPLETED======================================")


